export interface User {
  id: string;
  email: string;
  name: string;
}

export type ProcessingStatus = 'UPLOADING' | 'PROCESSING' | 'EMBEDDING' | 'READY' | 'FAILED';

export type BlockType = 'paragraph' | 'heading' | 'list' | 'table' | 'image';

export interface Block {
  type: BlockType;
  text: string;
  level?: number;
}

export interface Book {
  id: string;
  userId: string;
  title: string;
  author: string;
  coverImage: string;
  content: Block[]; // Array of structured content blocks
  status: ProcessingStatus;
  isEmbedded: boolean;
}

export interface Highlight {
  id: string;
  userId: string;
  bookId: string;
  text: string;
  paragraphIndex: number;
  summary?: string;
  flashcard?: Flashcard;
}

export interface Flashcard {
  question: string;
  answer: string;
}

export interface Illustration {
  id: string;
  userId: string;
  bookId: string;
  sourceText: string;
  imageUrl: string;
  style: string;
  isAutoGenerated: boolean;
  paragraphIndex: number;
  characterId?: string;
}

export interface CharacterProfile {
  id: string;
  bookId: string;
  name: string;
  description: string; // AI-generated description
}

export type IllustrationStyle = 'Watercolor' | 'Anime' | 'Realistic' | 'Cartoon' | 'Technical Sketch';

export enum Theme {
  Dark = 'dark',
  Light = 'light',
  Sepia = 'sepia',
}

export interface VectorEmbedding {
    id: string;
    bookId: string;
    paragraphIndex: number;
    text: string;
}

export interface Bookmark {
  id: string;
  userId: string;
  bookId: string;
  paragraphIndex: number;
  textSnippet: string;
}