import React, { useState, useRef, useEffect, useCallback, useMemo } from 'react';
import { Book, Highlight, Illustration, IllustrationStyle, Theme, User, Bookmark, Block, CharacterProfile } from '../types';
import { SelectionToolbar } from './SelectionToolbar';
import { IllustrationModal } from './IllustrationModal';
import { AiAssistantPanel } from './AiAssistantPanel';
import { NotesPanel } from './NotesPanel';
import { SearchPanel } from './SearchPanel';
import { generateSpeech } from '../services/geminiService';
import { api } from '../services/apiService';
import { CloseIcon, PaletteIcon, SparklesIcon, PencilIcon, PauseIcon, ChevronDownIcon, EyeIcon, SpeakerWaveIcon, MagicWandIcon, SearchIcon, BookmarkIcon, PlayIcon } from './icons';

// --- Audio Decoding Helpers ---
function decode(base64: string) {
  const binaryString = atob(base64);
  const len = binaryString.length;
  const bytes = new Uint8Array(len);
  for (let i = 0; i < len; i++) {
    bytes[i] = binaryString.charCodeAt(i);
  }
  return bytes;
}

async function decodeAudioData(
  data: Uint8Array,
  ctx: AudioContext,
): Promise<AudioBuffer> {
  // Raw PCM data assumes 24000 sample rate, 1 channel from Gemini API
  const sampleRate = 24000;
  const numChannels = 1;
  const dataInt16 = new Int16Array(data.buffer);
  const frameCount = dataInt16.length / numChannels;
  const buffer = ctx.createBuffer(numChannels, frameCount, sampleRate);

  for (let channel = 0; channel < numChannels; channel++) {
    const channelData = buffer.getChannelData(channel);
    for (let i = 0; i < frameCount; i++) {
      channelData[i] = dataInt16[i * numChannels + channel] / 32768.0;
    }
  }
  return buffer;
}

interface ReaderViewProps {
  book: Book;
  user: User;
  onClose: () => void;
}

const InlineIllustration: React.FC<{ illustration: Illustration }> = ({ illustration }) => (
    <div className="my-6 p-4 border border-gray-700/50 rounded-lg bg-black/20">
        <img src={illustration.imageUrl} alt={illustration.sourceText} className="w-full h-auto rounded-md aspect-video object-cover" />
        <p className="text-xs text-gray-400 mt-2 italic text-center">
            {illustration.isAutoGenerated ? `Scene illustration for the paragraph above.` : `Illustration for: "${illustration.sourceText}"`}
        </p>
    </div>
);

const ContentBlock: React.FC<{
    block: Block;
    index: number;
    setRef: (el: HTMLElement | null) => void;
    isFocus: boolean;
    isSpeaking: boolean;
    fontSize: number;
}> = ({ block, index, setRef, isFocus, isSpeaking, fontSize }) => {
    
    const commonClasses = `mb-6 font-serif text-justify leading-relaxed transition-all duration-500 rounded-md ${isFocus ? 'opacity-100' : 'opacity-40'} ${isSpeaking ? 'bg-readx-accent/20 p-2' : 'p-0'}`;

    switch (block.type) {
        case 'heading':
            return (
                <h2
                    ref={setRef}
                    data-paragraph-index={index}
                    className={`${commonClasses} font-bold`}
                    style={{ fontSize: `${fontSize * (1.5 - (block.level || 2) * 0.1)}px` }}
                >
                    {block.text}
                </h2>
            );
        case 'list':
            return (
                <p ref={setRef} data-paragraph-index={index} className={commonClasses} style={{ fontSize: `${fontSize}px` }}>
                    <span className="mr-2">•</span>{block.text}
                </p>
            );
        case 'paragraph':
        default:
            return (
                <p ref={setRef} data-paragraph-index={index} className={commonClasses} style={{ fontSize: `${fontSize}px` }}>
                    {block.text}
                </p>
            );
    }
};


export const ReaderView: React.FC<ReaderViewProps> = ({ book, user, onClose }) => {
  const [theme, setTheme] = useState<Theme>(Theme.Dark);
  const [fontSize, setFontSize] = useState(18);
  const [selection, setSelection] = useState<{ text: string; rect: DOMRect | null }>({ text: '', rect: null });
  const [activeParagraph, setActiveParagraph] = useState<number | null>(null);

  // Panels State
  const [isIllustrationModalOpen, setIsIllustrationModalOpen] = useState(false);
  const [isAiPanelOpen, setIsAiPanelOpen] = useState(false);
  const [aiInitialPrompt, setAiInitialPrompt] = useState<string | null>(null);
  const [isNotesPanelOpen, setIsNotesPanelOpen] = useState(true);
  const [isSearchPanelOpen, setIsSearchPanelOpen] = useState(false);
  
  // Content State
  const [illustrations, setIllustrations] = useState<Illustration[]>([]);
  const [highlights, setHighlights] = useState<Highlight[]>([]);
  const [bookmarks, setBookmarks] = useState<Bookmark[]>([]);
  const [characters, setCharacters] = useState<CharacterProfile[]>([]);
  
  // Feature States
  const [isFocusMode, setIsFocusMode] = useState(false);
  const [isAutoScrolling, setIsAutoScrolling] = useState(false);
  const [isReadingAloud, setIsReadingAloud] = useState(false);
  const [currentlySpeakingParagraph, setCurrentlySpeakingParagraph] = useState<number | null>(null);
  const [isAutoIllustrationMode, setIsAutoIllustrationMode] = useState(true);
  const [isGeneratingArt, setIsGeneratingArt] = useState(false);
  
  const readerContainerRef = useRef<HTMLDivElement>(null);
  const autoScrollIntervalRef = useRef<number | null>(null);
  const paragraphRefs = useRef<(HTMLElement | null)[]>([]);
  const autoIllustrationTimeoutRef = useRef<number | null>(null);
  const audioContextRef = useRef<AudioContext | null>(null);
  const currentAudioSourceRef = useRef<AudioBufferSourceNode | null>(null);

  // --- Data Fetching ---
  useEffect(() => {
    const fetchData = async () => {
        const [fetchedHighlights, fetchedIllustrations, fetchedBookmarks, fetchedCharacters] = await Promise.all([
            api.getHighlights(user.id, book.id),
            api.getIllustrations(user.id, book.id),
            api.getBookmarks(user.id, book.id),
            api.getCharacters(user.id, book.id)
        ]);
        setHighlights(fetchedHighlights);
        setIllustrations(fetchedIllustrations);
        setBookmarks(fetchedBookmarks);
        setCharacters(fetchedCharacters);
    };
    fetchData();
  }, [user.id, book.id]);

  // --- Core Selection Logic ---
  const handleMouseUp = useCallback(() => {
    const currentSelection = window.getSelection();
    if (currentSelection && currentSelection.toString().trim().length > 0) {
      const range = currentSelection.getRangeAt(0);
      const rect = range.getBoundingClientRect();
      const text = currentSelection.toString().trim();
      
      let element = range.commonAncestorContainer;
      if (element.nodeType === 3) element = element.parentNode!;

      const paragraphIndexAttr = (element as HTMLElement).closest('[data-paragraph-index]')?.getAttribute('data-paragraph-index');
      if(paragraphIndexAttr) {
         setActiveParagraph(parseInt(paragraphIndexAttr));
      }
      setSelection({ text, rect });
    } else {
      setSelection({ text: '', rect: null });
      setActiveParagraph(null);
    }
  }, []);

  useEffect(() => {
    document.addEventListener('mouseup', handleMouseUp);
    return () => document.removeEventListener('mouseup', handleMouseUp);
  }, [handleMouseUp]);

  const clearSelection = () => setSelection({ text: '', rect: null });

  // --- AI Handlers ---
  const handleIllustrate = () => setIsIllustrationModalOpen(true);
  const handleExplain = () => { setAiInitialPrompt(`Explain this: "${selection.text}"`); setIsAiPanelOpen(true); clearSelection(); };
  const handleTranslate = () => { setAiInitialPrompt(`Translate this: "${selection.text}"`); setIsAiPanelOpen(true); clearSelection(); };
  
  const handleGenerateIllustration = async (style: IllustrationStyle) => {
      if (!selection.text || activeParagraph === null) return;
      
      const illustrationData = {
          userId: user.id,
          bookId: book.id,
          sourceText: selection.text,
          style,
          isAutoGenerated: false,
          paragraphIndex: activeParagraph
      };
      
      setIsIllustrationModalOpen(false);
      clearSelection();
      
      try {
          const newIllustration = await api.createIllustration(illustrationData);
          setIllustrations(prev => [...prev, newIllustration]);
      } catch (error) {
           console.error("Failed to create illustration", error);
      }
  };

  const handleHighlight = async () => {
    if (activeParagraph === null) return;
    setIsNotesPanelOpen(true);
    
    const highlightData = {
        userId: user.id,
        bookId: book.id,
        text: selection.text,
        paragraphIndex: activeParagraph,
    };
    
    const tempId = `temp-hl-${Date.now()}`;
    // Optimistically add highlight
    setHighlights(prev => [...prev, { ...highlightData, id: tempId }]);
    clearSelection();

    try {
        const newHighlight = await api.createHighlight(highlightData);
        setHighlights(prev => prev.map(h => h.id === tempId ? newHighlight : h));
    } catch(error) {
        console.error("Failed to save highlight", error);
        setHighlights(prev => prev.filter(h => h.id !== tempId));
    }
  };

  // --- Utility Functions ---
  const scrollToParagraph = (index: number) => {
    paragraphRefs.current[index]?.scrollIntoView({ behavior: 'smooth', block: 'center' });
  };
  
  // --- Auto-Scroll Logic ---
  const stopAutoScroll = () => {
    if (autoScrollIntervalRef.current) {
        clearInterval(autoScrollIntervalRef.current);
        autoScrollIntervalRef.current = null;
    }
    setIsAutoScrolling(false);
  };

  useEffect(() => {
    if (isAutoScrolling) {
        autoScrollIntervalRef.current = window.setInterval(() => {
            if (readerContainerRef.current) {
                readerContainerRef.current.scrollBy({ top: 1, behavior: 'smooth' });
            }
        }, 50);
    } else {
        stopAutoScroll();
    }
    return stopAutoScroll;
  }, [isAutoScrolling]);

  // --- Focus & Auto-Illustration Mode Logic ---
  const [visibleParagraph, setVisibleParagraph] = useState(0);
  
  const handleAutoIllustration = useCallback(async (index: number) => {
    if (isGeneratingArt || illustrations.some(ill => ill.paragraphIndex === index && ill.isAutoGenerated)) return;
    setIsGeneratingArt(true);
    try {
      const paragraphText = book.content[index].text;
      const newIllustration = await api.generateAutoIllustration(user.id, book.id, index, paragraphText);
      if (newIllustration) {
        setIllustrations(prev => [...prev, newIllustration]);
        // Refresh characters as new ones might have been detected during this illustration generation
        const updatedCharacters = await api.getCharacters(user.id, book.id);
        setCharacters(updatedCharacters);
      }
    } catch (error) {
      console.error("Auto-illustration failed:", error);
    } finally {
      setIsGeneratingArt(false);
    }
  }, [isGeneratingArt, illustrations, book.id, user.id, book.content]);

  useEffect(() => {
    const observer = new IntersectionObserver(
        (entries) => {
            entries.forEach(entry => {
                if (entry.isIntersecting) {
                    const index = parseInt(entry.target.getAttribute('data-paragraph-index') || '0');
                    setVisibleParagraph(index);
                    if (isAutoIllustrationMode) {
                      if (autoIllustrationTimeoutRef.current) clearTimeout(autoIllustrationTimeoutRef.current);
                      autoIllustrationTimeoutRef.current = window.setTimeout(() => handleAutoIllustration(index), 2000);
                    }
                }
            });
        }, { threshold: 0.6, root: readerContainerRef.current }
    );

    paragraphRefs.current.forEach(p => { if(p) observer.observe(p) });
    return () => {
      observer.disconnect();
      if (autoIllustrationTimeoutRef.current) clearTimeout(autoIllustrationTimeoutRef.current);
    }
  }, [isAutoIllustrationMode, handleAutoIllustration]);
  
  const illustrationsByParagraph = useMemo(() => {
      return illustrations.reduce((acc, ill) => {
          (acc[ill.paragraphIndex] = acc[ill.paragraphIndex] || []).push(ill);
          return acc;
      }, {} as Record<number, Illustration[]>);
  }, [illustrations]);
  
  // --- Bookmark Logic ---
  const handleAddBookmark = async () => {
    const existingBookmark = bookmarks.find(b => b.paragraphIndex === visibleParagraph);
    if (existingBookmark) {
      await api.deleteBookmark(existingBookmark.id);
      setBookmarks(prev => prev.filter(b => b.id !== existingBookmark.id));
    } else {
      const newBookmark = await api.createBookmark({
        userId: user.id,
        bookId: book.id,
        paragraphIndex: visibleParagraph,
        textSnippet: book.content[visibleParagraph].text.substring(0, 100) + '...',
      });
      setBookmarks(prev => [...prev, newBookmark]);
    }
  };

  // --- Read Aloud Logic ---
  const playAudio = useCallback(async (index: number) => {
    if (index >= book.content.length) {
      setIsReadingAloud(false);
      return;
    }
    setCurrentlySpeakingParagraph(index);
    scrollToParagraph(index);
    try {
        const base64Audio = await generateSpeech(book.content[index].text);
        if (!audioContextRef.current) {
            audioContextRef.current = new (window.AudioContext || (window as any).webkitAudioContext)();
        }
        const audioBuffer = await decodeAudioData(decode(base64Audio), audioContextRef.current);
        const source = audioContextRef.current.createBufferSource();
        source.buffer = audioBuffer;
        source.connect(audioContextRef.current.destination);
        source.onended = () => {
            if (isReadingAloud) playAudio(index + 1);
        };
        source.start();
        currentAudioSourceRef.current = source;
    } catch (error) {
        console.error("Error playing audio:", error);
        setIsReadingAloud(false);
    }
  }, [book.content, isReadingAloud]);

  const toggleReadAloud = () => {
    if (isReadingAloud) {
      currentAudioSourceRef.current?.stop();
      setIsReadingAloud(false);
      setCurrentlySpeakingParagraph(null);
    } else {
      setIsReadingAloud(true);
      playAudio(visibleParagraph);
    }
  };

  useEffect(() => {
    if(!isReadingAloud && currentAudioSourceRef.current) {
        currentAudioSourceRef.current.stop();
        setCurrentlySpeakingParagraph(null);
    }
  }, [isReadingAloud]);

  const themeClasses = {
    [Theme.Dark]: 'bg-readx-dark text-readx-text-dark',
    [Theme.Light]: 'bg-readx-light text-readx-text-light',
    [Theme.Sepia]: 'bg-sepia text-sepia-text',
  };

  return (
    <div className={`fixed inset-0 flex flex-col font-sans transition-colors duration-300 ${themeClasses[theme]}`}>
      <header className="flex items-center justify-between p-4 bg-opacity-80 backdrop-blur-sm border-b border-gray-700/50 z-20">
        <div className="flex-1 flex items-center gap-4">
          <button onClick={onClose} className="hover:text-readx-accent transition-colors"><CloseIcon className="w-6 h-6" /></button>
          <button onClick={() => setIsSearchPanelOpen(!isSearchPanelOpen)} className={`transition-colors ${isSearchPanelOpen ? 'text-readx-accent' : 'hover:text-readx-accent'}`} title="Search Book"><SearchIcon className="w-6 h-6" /></button>
        </div>
        <div className="flex-1 text-center">
          <h2 className="font-bold text-lg truncate">{book.title}</h2>
          <p className="text-sm text-gray-400">{book.author}</p>
        </div>
        <div className="flex-1 flex justify-end items-center gap-4">
            <button onClick={() => setIsNotesPanelOpen(!isNotesPanelOpen)} className={`transition-colors ${isNotesPanelOpen ? 'text-readx-accent' : 'hover:text-readx-accent'}`} title="Notes & Highlights"><PencilIcon className="w-6 h-6" /></button>
            <button onClick={() => setIsAiPanelOpen(!isAiPanelOpen)} className={`transition-colors ${isAiPanelOpen ? 'text-readx-accent' : 'hover:text-readx-accent'}`} title="AI Assistant"><SparklesIcon className="w-6 h-6" /></button>
        </div>
      </header>

      <main className="flex-grow flex overflow-hidden">
        {isSearchPanelOpen && <SearchPanel bookId={book.id} onResultClick={(idx) => { scrollToParagraph(idx); setIsSearchPanelOpen(false); }} onClose={() => setIsSearchPanelOpen(false)} theme={theme} />}
        <div 
          ref={readerContainerRef}
          className="flex-grow overflow-y-auto p-8 md:p-12 lg:p-16 scroll-smooth"
          onWheel={() => { stopAutoScroll(); if (autoIllustrationTimeoutRef.current) clearTimeout(autoIllustrationTimeoutRef.current); }}
          onTouchStart={stopAutoScroll}
        >
          <div className="max-w-3xl mx-auto relative">
            {isGeneratingArt && (
              <div className="absolute -top-4 left-1/2 -translate-x-1/2 bg-readx-dark-secondary px-3 py-1 rounded-full text-xs flex items-center gap-2 shadow-lg">
                <MagicWandIcon className="w-4 h-4 text-readx-accent animate-pulse" />
                Generating art...
              </div>
            )}
            {book.content.map((block, index) => (
              <React.Fragment key={index}>
                <ContentBlock
                  block={block}
                  index={index}
                  setRef={el => paragraphRefs.current[index] = el}
                  isFocus={!isFocusMode || visibleParagraph === index}
                  isSpeaking={currentlySpeakingParagraph === index}
                  fontSize={fontSize}
                />
                {illustrationsByParagraph[index] && illustrationsByParagraph[index].map(ill => (
                  <InlineIllustration key={ill.id} illustration={ill}/>
                ))}
              </React.Fragment>
            ))}
          </div>
          {selection.text && selection.rect && (
            <SelectionToolbar
              rect={selection.rect}
              onExplain={handleExplain}
              onIllustrate={handleIllustrate}
              onHighlight={handleHighlight}
              onTranslate={handleTranslate}
              containerRef={readerContainerRef}
            />
          )}
        </div>

        {isAiPanelOpen && ( <AiAssistantPanel book={book} onClose={() => setIsAiPanelOpen(false)} theme={theme} initialPrompt={aiInitialPrompt} setInitialPrompt={setAiInitialPrompt} /> )}
        {isNotesPanelOpen && ( <NotesPanel onClose={() => setIsNotesPanelOpen(false)} highlights={highlights} illustrations={illustrations} bookmarks={bookmarks} characters={characters} onBookmarkClick={scrollToParagraph} onBookmarkDelete={async (id) => { await api.deleteBookmark(id); setBookmarks(prev => prev.filter(b => b.id !== id)); }} theme={theme} /> )}
      </main>

      <footer className="p-4 bg-opacity-80 backdrop-blur-sm border-t border-gray-700/50 flex items-center justify-center gap-x-6 gap-y-2 flex-wrap z-20">
        <div className="flex items-center gap-2">
          <span>A-</span>
          <input type="range" min="14" max="28" step="1" value={fontSize} onChange={(e) => setFontSize(parseInt(e.target.value))} className="w-24" />
          <span>A+</span>
        </div>
        <div className="flex items-center gap-2">
            <PaletteIcon className="w-5 h-5" />
            {[Theme.Dark, Theme.Light, Theme.Sepia].map(t => (
                <button key={t} onClick={() => setTheme(t)} className={`w-6 h-6 rounded-full border-2 ${theme === t ? 'border-readx-accent' : 'border-transparent'} ${t === Theme.Dark && 'bg-readx-dark'} ${t === Theme.Light && 'bg-readx-light'} ${t === Theme.Sepia && 'bg-sepia'}`}></button>
            ))}
        </div>
        <div className="flex items-center gap-4">
            <button onClick={handleAddBookmark} className={`flex items-center gap-1.5 ${bookmarks.some(b => b.paragraphIndex === visibleParagraph) ? 'text-readx-accent' : ''}`} title="Bookmark"><BookmarkIcon className="w-6 h-6" /></button>
            <button onClick={toggleReadAloud} className={`flex items-center gap-1.5 ${isReadingAloud ? 'text-readx-accent' : ''}`} title="Read Aloud">{isReadingAloud ? <PauseIcon className="w-6 h-6" /> : <PlayIcon className="w-6 h-6" />}</button>
            <button onClick={() => setIsAutoIllustrationMode(!isAutoIllustrationMode)} className={`flex items-center gap-1.5 ${isAutoIllustrationMode ? 'text-readx-accent' : ''}`} title="Auto-Illustrate"><MagicWandIcon className="w-6 h-6" /></button>
            <button onClick={() => setIsAutoScrolling(!isAutoScrolling)} className={`flex items-center gap-1.5 ${isAutoScrolling ? 'text-readx-accent' : ''}`} title="Auto Scroll"><ChevronDownIcon className={`w-6 h-6 ${isAutoScrolling ? 'animate-bounce' : ''}`} /></button>
            <button onClick={() => setIsFocusMode(!isFocusMode)} className={`flex items-center gap-1.5 ${isFocusMode ? 'text-readx-accent' : ''}`} title="Focus Mode"><EyeIcon className="w-6 h-6" /></button>
        </div>
      </footer>
      
      <IllustrationModal isOpen={isIllustrationModalOpen} onClose={() => setIsIllustrationModalOpen(false)} onGenerate={handleGenerateIllustration} selectedText={selection.text} />
    </div>
  );
};